apiVersion: v1
kind: Service
metadata:
  name: be-app
  namespace: default
  labels:
    app: be-app
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30037
  selector:
    app: be-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-app
  namespace: default
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: be-app
  template:
    metadata:
      labels:
        app: be-app
    spec:
#      imagePullSecrets:
#      - name: ap-southeast-1-ecr-registry
      containers:
      - name: be-app
        image: viraj/be-get-user-name:latest
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3 
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            cpu: "50m"
            memory: "100Mi"
        ports:
        - containerPort: 8081
        env:
          - name: "NAME"
            value: "Viraj"
